version: '3.1'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb_database:27017/?authSource=admin
      - SECRET=secret
      - PORT=3000
    depends_on:
      mongodb_database:
        condition: service_healthy

  mongodb_database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # no need to expose the port bc its used internally
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u blah -p $MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
    driver: local
