### POST: user test - username: admin, password: pasta123
### -> hash "$2b$10$eSva0B/bj59uovUI16YQOOLm946BCTYtjsjXrq2n9ssKZo/mmLyY2"
POST http://localhost:8080/api/users/signup
Content-Type: application/json

{
  "username": "admin",
  "password": "pasta123"
}

### POST: user test - username: admin, password: pasta123
### Response: {"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MmY2ZTczNDVlM2ZiMDgwZDA3MGZmMjkiLCJpYXQiOjE2NjAzNDgyMjF9.WgvZxJHSIzC7gntgoiZ4RV3-fp41ij9ZdHqURKkexBU"}
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "pasta123"
}

### POST: seed user test - username: jason, password: flower
### Response {"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imphc29uIiwiaWQiOiI2MmY2ZTcxNjVlM2ZiMDgwZDA3MGZmMWYiLCJpYXQiOjE2NjAzNDg1NzZ9.MrNHWHYcOp_SJgsKpf849WqN2LOn3Kdg0u6Cy0htOJU"}
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "jason",
  "password": "flower"
}

### Failed Login
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "jason",
  "password": "flower123"
}