### POST: user test - username: admin, password: pasta123
### -> hash "$2b$10$eSva0B/bj59uovUI16YQOOLm946BCTYtjsjXrq2n9ssKZo/mmLyY2"
POST http://localhost:8080/api/users/signup
Content-Type: application/json

{
  "username": "admin",
  "password": "pasta123"
}

### POST: user test - username: admin, password: pasta123
### Response: {"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MmY5ZTM3MjI3NmJlZWY0MDU3YjUyZjUiLCJpYXQiOjE2NjA1NDM4Njl9.Zf61mJGvm3L-7WW1IoQ4Vc87FqyCZunHpf_X5jwdEf4"}
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "pasta123"
}

### POST: seed user test - username: jason, password: flower
### Response {"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imphc29uIiwiaWQiOiI2MmY4N2VjOGExNDVjNjI0Y2U1OWViOTIiLCJpYXQiOjE2NjA1NDM4ODV9.DxxDnukh3jr2-hvkYT8Q8oINrMIOWmXmclMx8q1g5-U"}
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "jason",
  "password": "flower"
}

### Failed Login
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "jason",
  "password": "flower123"
}